import 'package:flutter/material.dart';
import '../retailer_models/retailer_inventory_item_model.dart';

class AddInventoryDialog extends StatefulWidget {
  final Function(RetailerInventoryItemModel item) onSave;

  const AddInventoryDialog({super.key, required this.onSave});

  @override
  State<AddInventoryDialog> createState() => _AddInventoryDialogState();
}

class _AddInventoryDialogState extends State<AddInventoryDialog> {
  final _formKey = GlobalKey<FormState>();
  
  final _nameController = TextEditingController();
  final _categoryController = TextEditingController();
  final _costPriceController = TextEditingController(); // Added Cost Price
  final _priceController = TextEditingController(); // Selling Price
  final _stockController = TextEditingController();
  final _imageUrlController = TextEditingController();
  final _descriptionController = TextEditingController();

  void _handleSubmit() {
    if (_formKey.currentState?.validate() ?? false) {
      
      final newItem = RetailerInventoryItemModel(
        id: '', // ID will be generated by the Repo/Firebase push()
        name: _nameController.text,
        category: _categoryController.text,
        costPrice: double.tryParse(_costPriceController.text) ?? 0.0,
        price: double.tryParse(_priceController.text) ?? 0.0,
        stockremain: int.tryParse(_stockController.text) ?? 0,
        imageUrl: _imageUrlController.text.isNotEmpty 
            ? _imageUrlController.text 
            : 'https://placehold.co/400x400/grey/fff?text=No+Image',
        description: _descriptionController.text,
        isLive: false,
        listedQty: 0,
      );

      widget.onSave(newItem);
      Navigator.of(context).pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Add New Inventory Item'),
      content: SizedBox(
        width: 500,
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                _buildTextField(_nameController, 'Product Name'),
                _buildTextField(_categoryController, 'Category'),
                Row(
                  children: [
                    Expanded(child: _buildTextField(_costPriceController, 'Cost Price (Buy)', isNumber: true)),
                    const SizedBox(width: 10),
                    Expanded(child: _buildTextField(_priceController, 'Selling Price', isNumber: true)),
                  ],
                ),
                _buildTextField(_stockController, 'Stock Remaining', isNumber: true),
                _buildTextField(_imageUrlController, 'Image URL (Optional)', isRequired: false),
                _buildTextField(_descriptionController, 'Description (Optional)', isRequired: false, maxLines: 3),
              ],
            ),
          ),
        ),
      ),
      actions: [
        TextButton(
          child: const Text('Cancel'),
          onPressed: () => Navigator.of(context).pop(),
        ),
        ElevatedButton(
          child: const Text('Save'),
          onPressed: _handleSubmit,
        ),
      ],
    );
  }

  Widget _buildTextField(TextEditingController controller, String label, {bool isNumber = false, bool isRequired = true, int maxLines = 1}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: TextFormField(
        controller: controller,
        decoration: InputDecoration(
          labelText: label,
          border: const OutlineInputBorder(),
          isDense: true,
        ),
        keyboardType: isNumber ? TextInputType.number : TextInputType.text,
        maxLines: maxLines,
        validator: (value) {
          if (isRequired && (value == null || value.isEmpty)) {
            return '$label is required';
          }
          if (isNumber && value != null && value.isNotEmpty && double.tryParse(value) == null) {
            return 'Enter valid number';
          }
          return null;
        },
      ),
    );
  }
}