// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFNPM4cIn5dy5EoQoRuqeTCxbwWk1cnwg',
    appId: '1:64211053051:web:5693dc0a272954eef4c35e',
    messagingSenderId: '64211053051',
    projectId: 'azt-playground-app',
    authDomain: 'azt-playground-app.firebaseapp.com',
    storageBucket: 'azt-playground-app.firebasestorage.app',
    measurementId: 'G-NQCT7LCPJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiC3BnNnf6bpUXb7ekKEIx2tsYVbO5nVc',
    appId: '1:64211053051:android:823078095757d815f4c35e',
    messagingSenderId: '64211053051',
    projectId: 'azt-playground-app',
    storageBucket: 'azt-playground-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjtjbA0PkBBROTd9GGtmdQiusNdA0rarY',
    appId: '1:64211053051:ios:8feaa9f42f9f978ef4c35e',
    messagingSenderId: '64211053051',
    projectId: 'azt-playground-app',
    storageBucket: 'azt-playground-app.firebasestorage.app',
    iosBundleId: 'com.example.azt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjtjbA0PkBBROTd9GGtmdQiusNdA0rarY',
    appId: '1:64211053051:ios:8feaa9f42f9f978ef4c35e',
    messagingSenderId: '64211053051',
    projectId: 'azt-playground-app',
    storageBucket: 'azt-playground-app.firebasestorage.app',
    iosBundleId: 'com.example.azt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFNPM4cIn5dy5EoQoRuqeTCxbwWk1cnwg',
    appId: '1:64211053051:web:1e668746cff39785f4c35e',
    messagingSenderId: '64211053051',
    projectId: 'azt-playground-app',
    authDomain: 'azt-playground-app.firebaseapp.com',
    storageBucket: 'azt-playground-app.firebasestorage.app',
    measurementId: 'G-6ZNXRV3SWQ',
  );
}
